# Generated by Django 2.2.28 on 2022-12-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221205_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gitcode',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
